### ISSUE TITLE
Redirect to new repository

### ISSUE THREAD

**Issue by d-simon** [stephband/sound.io#1]
Liked your talk at SwissJS!

Small heads up: This repository is the first result on google for me when looking up `soundio`.
I think it'd be great to be redirected (through a short note at very least) from this seemingly inactive repository to https://github.com/soundio/soundio

**Comment by stephband** [comment]
Good catch, thank you. Fixed!

––––––––––––
http://sound.io
http://cruncher.ch
http://stephen.band
